services:
    pw-ui:
      init: true
      image: ghcr.io/wisetrout/playwright-ui:latest
      ports:
        - ${TESTS_MENU_PORT:-3000}:3000
        - ${TESTS_RESULTS_PORT:-9323}:9323
      environment:
        - TESTS_MENU_PORT
        - TESTS_RESULTS_PORT
      security_opt:
        - seccomp=seccomp_profile.json
      volumes:
        - type: bind
          source: ./hooks
          target: /app/hooks
        - type: bind
          source: ./tests
          target: /app/tests
        - type: bind
          source: ./metadata
          target: /app/metadata
        - type: bind
          source: ./settings
          target: /app/settings
        - type: bind
          source: ./ui-lib
          target: /app/ui-lib
        #  Create empty file password.txt and uncomment the following lines to use authorization.
        #  To reset the password, empty the contents of existing password.txt
        # - type: bind
        #   source: ./password.txt
        #   target: /app/password.txt
        # Uncomment this to add npm packages to project
        # - type: bind
        #   source: ./package.json
        #   target: /app/aux-dependencies/package.json